### ISSUE TITLE
What python version is required for this package?

### ISSUE THREAD

**Issue by opain** [qlu-lab/X-Wing#2]
Hello,

Excellent work. Excited to use the tool.

What python version is required for this package? Given it requires scipy=1.2.0, I guess Python 3.6?

Many thanks,

Oliver Pain

**Comment by jmiao24** [comment]
Hi Oliver,

Thank you for your interest in X-Wing! I have tested our package with Python versions 3.6, 3.8, and 3.10, and it works for all of them. It’s important to note that I just updated the package to address a deprecated function in scipy. Therefore, please ensure you are using the latest version available on GitHub.

Best,
Jiacheng

**Comment by opain** [comment]
Great! Thank you Jiacheng!
