### ISSUE TITLE
Allowing multiple target populations for LOGODetect

### ISSUE THREAD

**Issue by opain** [qlu-lab/X-Wing#3]
Hi,

In case useful, I made a small edit to LOGODetect to allow multiple target populations. I pushed the commit to forked version of your repo: https://github.com/qlu-lab/X-Wing/compare/main...opain:X-Wing:main. The tracked chnages aren't highlighting properly, but the changes are in these two chunks:
- https://github.com/opain/X-Wing/blob/e9fcc264266e0e884323311816bfe20053fd3f7a/LOGODetect.R#L115-L116
- https://github.com/opain/X-Wing/blob/e9fcc264266e0e884323311816bfe20053fd3f7a/LOGODetect.R#L819-L840

This is handy when you want to annotations that allow you to predict into each population, without running LOGODetect multiple times with a different --target_pop parameter.

**Comment by jmiao24** [comment]
Hi ollie,

Thank you so much for doing this—it’s great! 

Best,
Jiacheng
